gostja	gostjannu	N;SG;ESS
gostja	gostjaspäi	N;SG;IN+ABL
gostja	gostjattah	N;SG;PRIV
gostja	gostjain	N;PL;GEN
gostja	gostjal	N;SG;AT+ESS
gostja	gostja	N;SG;NOM
gostja	gostjainke	N;PL;COM
gostja	gostjainnu	N;PL;ESS
gostja	gostjail	N;PL;AT+ESS
gostja	gostjat	N;PL;ACC
gostja	gostjači	N;SG;PROL
gostja	gostjaittah	N;PL;PRIV
gostja	gostjaiči	N;PL;PROL
gostja	gostjaa	N;SG;PRT
gostja	gostjalpäi	N;SG;AT+ABL
gostja	gostjain	N;PL;INS
gostja	gostjaikse	N;PL;TRANS
gostja	gostjan	N;SG;GEN
gostja	gostjah	N;SG;IN+ALL
gostja	gostjale	N;SG;AT+ALL
gostja	gostjais	N;PL;IN+ESS
gostja	gostjaile	N;PL;AT+ALL
gostja	gostjaispäi	N;PL;IN+ABL
gostja	gostjat	N;PL;NOM
gostja	gostjai	N;PL;PRT
gostja	gostjas	N;SG;IN+ESS
gostja	gostjakse	N;SG;TRANS
gostja	gostjaih	N;PL;IN+ALL
gostja	gostjanke	N;SG;COM
gostja	gostjailpäi	N;PL;AT+ABL
gostja	gostjan	N;SG;ACC

helsingiläine	helsingiläzelpäi	ADJ;SG;AT+ABL
helsingiläine	helsingiläzile	ADJ;PL;AT+ALL
helsingiläine	helsingiläzikse	ADJ;PL;TRANS
helsingiläine	helsingiläzes	ADJ;SG;IN+ESS
helsingiläine	helsingiläzettäh	ADJ;SG;PRIV
helsingiläine	helsingiläzih	ADJ;PL;IN+ALL
helsingiläine	helsingiläzel	ADJ;SG;AT+ESS
helsingiläine	helsingiläzilpäi	ADJ;PL;AT+ABL
helsingiläine	helsingiläzekse	ADJ;SG;TRANS
helsingiläine	helsingilästy	ADJ;SG;PRT
helsingiläine	helsingiläzil	ADJ;PL;AT+ESS
helsingiläine	helsingiläzittäh	ADJ;PL;PRIV
helsingiläine	helsingiläzenke	ADJ;SG;COM
helsingiläine	helsingiläzien	ADJ;PL;GEN
helsingiläine	helsingiläzeči	ADJ;SG;PROL
helsingiläine	helsingiläine	ADJ;SG;NOM
helsingiläine	helsingiläzet	ADJ;PL;NOM
helsingiläine	helsingiläzele	ADJ;SG;AT+ALL
helsingiläine	helsingiläzinke	ADJ;PL;COM
helsingiläine	helsingiläzis	ADJ;PL;IN+ESS
helsingiläine	helsingiläzen	ADJ;SG;GEN
helsingiläine	helsingiläzispäi	ADJ;PL;IN+ABL
helsingiläine	helsingiläzeh	ADJ;SG;IN+ALL
helsingiläine	helsingiläzinny	ADJ;PL;ESS
helsingiläine	helsingiläzespäi	ADJ;SG;IN+ABL
helsingiläine	helsingiläzin	ADJ;PL;INS
helsingiläine	helsingiläzet	ADJ;PL;ACC
helsingiläine	helsingiläziči	ADJ;PL;PROL
helsingiläine	helsingiläzii	ADJ;PL;PRT
helsingiläine	helsingiläzen	ADJ;SG;ACC
helsingiläine	helsingiläzenny	ADJ;SG;ESS

helsingiläine	helsingiläzien	N;PL;GEN
helsingiläine	helsingiläzile	N;PL;AT+ALL
helsingiläine	helsingiläzet	N;PL;NOM
helsingiläine	helsingiläzen	N;SG;ACC
helsingiläine	helsingiläziči	N;PL;PROL
helsingiläine	helsingiläzii	N;PL;PRT
helsingiläine	helsingiläzinny	N;PL;ESS
helsingiläine	helsingiläzele	N;SG;AT+ALL
helsingiläine	helsingiläzin	N;PL;INS
helsingiläine	helsingiläzilpäi	N;PL;AT+ABL
helsingiläine	helsingiläzespäi	N;SG;IN+ABL
helsingiläine	helsingiläzes	N;SG;IN+ESS
helsingiläine	helsingiläzis	N;PL;IN+ESS
helsingiläine	helsingiläzet	N;PL;ACC
helsingiläine	helsingiläzil	N;PL;AT+ESS
helsingiläine	helsingiläzih	N;PL;IN+ALL
helsingiläine	helsingiläzenke	N;SG;COM
helsingiläine	helsingiläzenny	N;SG;ESS
helsingiläine	helsingiläzeh	N;SG;IN+ALL
helsingiläine	helsingiläzikse	N;PL;TRANS
helsingiläine	helsingiläzettäh	N;SG;PRIV
helsingiläine	helsingiläzekse	N;SG;TRANS
helsingiläine	helsingiläzel	N;SG;AT+ESS
helsingiläine	helsingiläzen	N;SG;GEN
helsingiläine	helsingiläzinke	N;PL;COM
helsingiläine	helsingiläzispäi	N;PL;IN+ABL
helsingiläine	helsingiläzittäh	N;PL;PRIV
helsingiläine	helsingiläzelpäi	N;SG;AT+ABL
helsingiläine	helsingiläzeči	N;SG;PROL
helsingiläine	helsingilästy	N;SG;PRT
helsingiläine	helsingiläine	N;SG;NOM

aiguine	aiguzinnu	ADJ;PL;ESS
aiguine	aiguzekse	ADJ;SG;TRANS
aiguine	aiguzen	ADJ;SG;GEN
aiguine	aiguine	ADJ;SG;NOM
aiguine	aiguzennu	ADJ;SG;ESS
aiguine	aiguzespäi	ADJ;SG;IN+ABL
aiguine	aiguzilpäi	ADJ;PL;AT+ABL
aiguine	aigustu	ADJ;SG;PRT
aiguine	aiguzikse	ADJ;PL;TRANS
aiguine	aiguzinke	ADJ;PL;COM
aiguine	aiguzis	ADJ;PL;IN+ESS
aiguine	aiguzeh	ADJ;SG;IN+ALL
aiguine	aiguzet	ADJ;PL;NOM
aiguine	aiguzelpäi	ADJ;SG;AT+ABL
aiguine	aiguzes	ADJ;SG;IN+ESS
aiguine	aiguzil	ADJ;PL;AT+ESS
aiguine	aiguzet	ADJ;PL;ACC
aiguine	aiguzeči	ADJ;SG;PROL
aiguine	aiguzel	ADJ;SG;AT+ESS
aiguine	aiguzii	ADJ;PL;PRT
aiguine	aiguzien	ADJ;PL;GEN
aiguine	aiguzile	ADJ;PL;AT+ALL
aiguine	aiguziči	ADJ;PL;PROL
aiguine	aiguzenke	ADJ;SG;COM
aiguine	aiguzih	ADJ;PL;IN+ALL
aiguine	aiguzispäi	ADJ;PL;IN+ABL
aiguine	aiguzen	ADJ;SG;ACC
aiguine	aiguzittah	ADJ;PL;PRIV
aiguine	aiguzin	ADJ;PL;INS
aiguine	aiguzele	ADJ;SG;AT+ALL
aiguine	aiguzettah	ADJ;SG;PRIV

aiguine	aiguzele	N;SG;AT+ALL
aiguine	aiguzespäi	N;SG;IN+ABL
aiguine	aiguzikse	N;PL;TRANS
aiguine	aiguzin	N;PL;INS
aiguine	aiguine	N;SG;NOM
aiguine	aiguzekse	N;SG;TRANS
aiguine	aiguzinnu	N;PL;ESS
aiguine	aiguzel	N;SG;AT+ESS
aiguine	aiguzinke	N;PL;COM
aiguine	aiguzes	N;SG;IN+ESS
aiguine	aiguzile	N;PL;AT+ALL
aiguine	aiguzeh	N;SG;IN+ALL
aiguine	aiguzennu	N;SG;ESS
aiguine	aiguzii	N;PL;PRT
aiguine	aiguzis	N;PL;IN+ESS
aiguine	aiguzil	N;PL;AT+ESS
aiguine	aiguzen	N;SG;GEN
aiguine	aiguziči	N;PL;PROL
aiguine	aiguzet	N;PL;NOM
aiguine	aiguzet	N;PL;ACC
aiguine	aiguzen	N;SG;ACC
aiguine	aiguzien	N;PL;GEN
aiguine	aiguzittah	N;PL;PRIV
aiguine	aiguzilpäi	N;PL;AT+ABL
aiguine	aiguzettah	N;SG;PRIV
aiguine	aigustu	N;SG;PRT
aiguine	aiguzelpäi	N;SG;AT+ABL
aiguine	aiguzeči	N;SG;PROL
aiguine	aiguzenke	N;SG;COM
aiguine	aiguzih	N;PL;IN+ALL
aiguine	aiguzispäi	N;PL;IN+ABL

jogi	jovet	N;PL;NOM
jogi	jogilois	N;PL;IN+ESS
jogi	jogih	N;SG;IN+ALL
jogi	joven	N;SG;GEN
jogi	joven	N;SG;ACC
jogi	jogiloilpäi	N;PL;AT+ABL
jogi	jovet	N;PL;ACC
jogi	jogi	N;SG;NOM
jogi	jogiloittah	N;PL;PRIV
jogi	jovennu	N;SG;ESS
jogi	jovelpäi	N;SG;AT+ABL
jogi	jovettah	N;SG;PRIV
jogi	jogiloi	N;PL;PRT
jogi	jogiloin	N;PL;GEN
jogi	jogiloispäi	N;PL;IN+ABL
jogi	joves	N;SG;IN+ESS
jogi	jogiloinnu	N;PL;ESS
jogi	joveči	N;SG;PROL
jogi	jogiloil	N;PL;AT+ESS
jogi	jovespäi	N;SG;IN+ABL
jogi	jovele	N;SG;AT+ALL
jogi	jovekse	N;SG;TRANS
jogi	jovel	N;SG;AT+ESS
jogi	jogiloih	N;PL;IN+ALL
jogi	jovenke	N;SG;COM
jogi	jogiloile	N;PL;AT+ALL
jogi	jogiloinke	N;PL;COM
jogi	jogiloiči	N;PL;PROL
jogi	jogiloin	N;PL;INS
jogi	jogiloikse	N;PL;TRANS
jogi	jogie	N;SG;PRT

järvi	järvilöis	N;PL;IN+ESS
järvi	järvilöispäi	N;PL;IN+ABL
järvi	järvekse	N;SG;TRANS
järvi	järvettäh	N;SG;PRIV
järvi	järven	N;SG;GEN
järvi	järvilöinke	N;PL;COM
järvi	järvelpäi	N;SG;AT+ABL
järvi	järvilöiči	N;PL;PROL
järvi	järvele	N;SG;AT+ALL
järvi	järvet	N;PL;NOM
järvi	järven	N;SG;ACC
järvi	järvie	N;SG;PRT
järvi	järvespäi	N;SG;IN+ABL
järvi	järveh	N;SG;IN+ALL
järvi	järvilöih	N;PL;IN+ALL
järvi	järvilöikse	N;PL;TRANS
järvi	järvel	N;SG;AT+ESS
järvi	järvenke	N;SG;COM
järvi	järvilöinny	N;PL;ESS
järvi	järvilöi	N;PL;PRT
järvi	järvi	N;SG;NOM
järvi	järves	N;SG;IN+ESS
järvi	järvilöile	N;PL;AT+ALL
järvi	järvilöin	N;PL;INS
järvi	järvilöittäh	N;PL;PRIV
järvi	järvet	N;PL;ACC
järvi	järvilöil	N;PL;AT+ESS
järvi	järvilöilpäi	N;PL;AT+ABL
järvi	järvilöin	N;PL;GEN
järvi	järvenny	N;SG;ESS
järvi	järveči	N;SG;PROL

kala	kalattah	N;SG;PRIV
kala	kaloikse	N;PL;TRANS
kala	kalat	N;PL;ACC
kala	kaloilpäi	N;PL;AT+ABL
kala	kaloinke	N;PL;COM
kala	kaloile	N;PL;AT+ALL
kala	kaloispäi	N;PL;IN+ABL
kala	kalači	N;SG;PROL
kala	kaloih	N;PL;IN+ALL
kala	kalua	N;SG;PRT
kala	kaloil	N;PL;AT+ESS
kala	kaloinnu	N;PL;ESS
kala	kaloi	N;PL;PRT
kala	kalakse	N;SG;TRANS
kala	kaloin	N;PL;INS
kala	kalan	N;SG;GEN
kala	kalalpäi	N;SG;AT+ABL
kala	kalan	N;SG;ACC
kala	kalannu	N;SG;ESS
kala	kalat	N;PL;NOM
kala	kalale	N;SG;AT+ALL
kala	kalaspäi	N;SG;IN+ABL
kala	kalah	N;SG;IN+ALL
kala	kala	N;SG;NOM
kala	kaloittah	N;PL;PRIV
kala	kalal	N;SG;AT+ESS
kala	kalanke	N;SG;COM
kala	kalois	N;PL;IN+ESS
kala	kalas	N;SG;IN+ESS
kala	kaloiči	N;PL;PROL
kala	kaloin	N;PL;GEN

kanzalaine	kanzalazikse	N;PL;TRANS
kanzalaine	kanzalazilpäi	N;PL;AT+ABL
kanzalaine	kanzalazil	N;PL;AT+ESS
kanzalaine	kanzalazenke	N;SG;COM
kanzalaine	kanzalazet	N;PL;ACC
kanzalaine	kanzalazel	N;SG;AT+ESS
kanzalaine	kanzalazinnu	N;PL;ESS
kanzalaine	kanzalazien	N;PL;GEN
kanzalaine	kanzalazeči	N;SG;PROL
kanzalaine	kanzalazespäi	N;SG;IN+ABL
kanzalaine	kanzalazin	N;PL;INS
kanzalaine	kanzalazen	N;SG;GEN
kanzalaine	kanzalazih	N;PL;IN+ALL
kanzalaine	kanzalazittah	N;PL;PRIV
kanzalaine	kanzalazennu	N;SG;ESS
kanzalaine	kanzalazis	N;PL;IN+ESS
kanzalaine	kanzalazispäi	N;PL;IN+ABL
kanzalaine	kanzalazele	N;SG;AT+ALL
kanzalaine	kanzalazinke	N;PL;COM
kanzalaine	kanzalazeh	N;SG;IN+ALL
kanzalaine	kanzalazen	N;SG;ACC
kanzalaine	kanzalazelpäi	N;SG;AT+ABL
kanzalaine	kanzalazii	N;PL;PRT
kanzalaine	kanzalazes	N;SG;IN+ESS
kanzalaine	kanzalaine	N;SG;NOM
kanzalaine	kanzalastu	N;SG;PRT
kanzalaine	kanzalazet	N;PL;NOM
kanzalaine	kanzalazekse	N;SG;TRANS
kanzalaine	kanzalazettah	N;SG;PRIV
kanzalaine	kanzalaziči	N;PL;PROL
kanzalaine	kanzalazile	N;PL;AT+ALL

kezä	kezinke	N;PL;COM
kezä	kezäspäi	N;SG;IN+ABL
kezä	kezinny	N;PL;ESS
kezä	kezis	N;PL;IN+ESS
kezä	kezilpäi	N;PL;AT+ABL
kezä	kezäle	N;SG;AT+ALL
kezä	kezispäi	N;PL;IN+ABL
kezä	kezäči	N;SG;PROL
kezä	kezänny	N;SG;ESS
kezä	kezän	N;SG;ACC
kezä	keziä	N;SG;PRT
kezä	kezittäh	N;PL;PRIV
kezä	kezäs	N;SG;IN+ESS
kezä	kezäkse	N;SG;TRANS
kezä	kezin	N;PL;INS
kezä	kezä	N;SG;NOM
kezä	keziči	N;PL;PROL
kezä	kezäh	N;SG;IN+ALL
kezä	kezikse	N;PL;TRANS
kezä	kezile	N;PL;AT+ALL
kezä	kezien	N;PL;GEN
kezä	kezän	N;SG;GEN
kezä	kezättäh	N;SG;PRIV
kezä	kezät	N;PL;NOM
kezä	kezii	N;PL;PRT
kezä	kezät	N;PL;ACC
kezä	kezälpäi	N;SG;AT+ABL
kezä	kezänke	N;SG;COM
kezä	kezih	N;PL;IN+ALL
kezä	kezäl	N;SG;AT+ESS
kezä	kezil	N;PL;AT+ESS

kofeidu	kofeidukse	N;SG;TRANS
kofeidu	kofeidun	N;SG;GEN
kofeidu	kofeidul	N;SG;AT+ESS
kofeidu	kofeiduikse	N;PL;TRANS
kofeidu	kofeiduin	N;PL;INS
kofeidu	kofeiduienke	N;PL;COM
kofeidu	kofeiduinnu	N;PL;ESS
kofeidu	kofeidunke	N;SG;COM
kofeidu	kofeiduttah	N;SG;PRIV
kofeidu	kofeidunnu	N;SG;ESS
kofeidu	kofeidut	N;PL;NOM
kofeidu	kofeiduis	N;PL;IN+ESS
kofeidu	kofeiduil	N;PL;AT+ESS
kofeidu	kofeidoi	N;PL;PRT
kofeidu	kofeidulpäi	N;SG;AT+ABL
kofeidu	kofeiduiči	N;PL;PROL
kofeidu	kofeidua	N;SG;PRT
kofeidu	kofeiduispäi	N;PL;IN+ABL
kofeidu	kofeidus	N;SG;IN+ESS
kofeidu	kofeidut	N;PL;ACC
kofeidu	kofeiduittah	N;PL;PRIV
kofeidu	kofeiduh	N;SG;IN+ALL
kofeidu	kofeiduilpäi	N;PL;AT+ABL
kofeidu	kofeidu	N;SG;NOM
kofeidu	kofeidule	N;SG;AT+ALL
kofeidu	kofeidupäi	N;SG;IN+ABL
kofeidu	kofeiduči	N;SG;PROL
kofeidu	kofeiduin	N;PL;GEN
kofeidu	kofeidun	N;SG;ACC
kofeidu	kofeiduih	N;PL;IN+ALL
kofeidu	kofeiduile	N;PL;AT+ALL

kuu	kuuttah	N;SG;PRIV
kuu	kuuloilpäi	N;PL;AT+ABL
kuu	kuuloiči	N;PL;PROL
kuu	kuunke	N;SG;COM
kuu	kuule	N;SG;AT+ALL
kuu	kuuloih	N;PL;IN+ALL
kuu	kuuloispäi	N;PL;IN+ABL
kuu	kuuspäi	N;SG;IN+ABL
kuu	kuuloinnu	N;PL;ESS
kuu	kuuloin	N;PL;GEN
kuu	kuulpäi	N;SG;AT+ABL
kuu	kuuloittah	N;PL;PRIV
kuu	kuuloinke	N;PL;COM
kuu	kuul	N;SG;AT+ESS
kuu	kuukse	N;SG;TRANS
kuu	kuuči	N;SG;PROL
kuu	kuun	N;SG;GEN
kuu	kuuloi	N;PL;PRT
kuu	kuulois	N;PL;IN+ESS
kuu	kuuloikse	N;PL;TRANS
kuu	kuut	N;PL;NOM
kuu	kuudu	N;SG;PRT
kuu	kuunnu	N;SG;ESS
kuu	kuuloil	N;PL;AT+ESS
kuu	kuut	N;PL;ACC
kuu	kuu	N;SG;NOM
kuu	kuuloin	N;PL;INS
kuu	kuus	N;SG;IN+ESS
kuu	kuuloile	N;PL;AT+ALL
kuu	kuuh	N;SG;IN+ALL
kuu	kuun	N;SG;ACC

mandžoi	mandžoloin	N;PL;GEN
mandžoi	mandžoinke	N;SG;COM
mandžoi	mandžoidu	N;SG;PRT
mandžoi	mandžoinnu	N;SG;ESS
mandžoi	mandžoloin	N;PL;INS
mandžoi	mandžoloi	N;PL;PRT
mandžoi	mandžois	N;SG;IN+ESS
mandžoi	mandžoloile	N;PL;AT+ALL
mandžoi	mandžoi	N;SG;NOM
mandžoi	mandžoloispäi	N;PL;IN+ABL
mandžoi	mandžoin	N;SG;ACC
mandžoi	mandžoloinnu	N;PL;ESS
mandžoi	mandžoih	N;SG;IN+ALL
mandžoi	mandžoloih	N;PL;IN+ALL
mandžoi	mandžolois	N;PL;IN+ESS
mandžoi	mandžoile	N;SG;AT+ALL
mandžoi	mandžoloiči	N;PL;PROL
mandžoi	mandžoittah	N;SG;PRIV
mandžoi	mandžoloinke	N;PL;COM
mandžoi	mandžoiči	N;SG;PROL
mandžoi	mandžoloil	N;PL;AT+ESS
mandžoi	mandžoloilpäi	N;PL;AT+ABL
mandžoi	mandžoloikse	N;PL;TRANS
mandžoi	mandžoilpäi	N;SG;AT+ABL
mandžoi	mandžoikse	N;SG;TRANS
mandžoi	mandžoin	N;SG;GEN
mandžoi	mandžoit	N;PL;NOM
mandžoi	mandžoit	N;PL;ACC
mandžoi	mandžoil	N;SG;AT+ESS
mandžoi	mandžoispäi	N;SG;IN+ABL
mandžoi	mandžoloittah	N;PL;PRIV

mua	mualpäi	N;SG;AT+ABL
mua	muakse	N;SG;TRANS
mua	muaspäi	N;SG;IN+ABL
mua	mualoinke	N;PL;COM
mua	mualoin	N;PL;INS
mua	mualoiči	N;PL;PROL
mua	muan	N;SG;ACC
mua	mualoi	N;PL;PRT
mua	mualoinnu	N;PL;ESS
mua	muanke	N;SG;COM
mua	muas	N;SG;IN+ESS
mua	muale	N;SG;AT+ALL
mua	mualoile	N;PL;AT+ALL
mua	mualoil	N;PL;AT+ESS
mua	mualoih	N;PL;IN+ALL
mua	mualois	N;PL;IN+ESS
mua	muah	N;SG;IN+ALL
mua	muattah	N;SG;PRIV
mua	mualoin	N;PL;GEN
mua	muannu	N;SG;ESS
mua	mua	N;SG;NOM
mua	muat	N;PL;ACC
mua	mual	N;SG;AT+ESS
mua	mualoittah	N;PL;PRIV
mua	mualoikse	N;PL;TRANS
mua	muan	N;SG;GEN
mua	muadu	N;SG;PRT
mua	mualoispäi	N;PL;IN+ABL
mua	muat	N;PL;NOM
mua	mualoilpäi	N;PL;AT+ABL
mua	muači	N;SG;PROL

naine	naizil	N;PL;AT+ESS
naine	naine	N;SG;NOM
naine	naizinnu	N;PL;ESS
naine	naizis	N;PL;IN+ESS
naine	naistu	N;SG;PRT
naine	naizien	N;PL;GEN
naine	naizin	N;PL;INS
naine	naizele	N;SG;AT+ALL
naine	naizenke	N;SG;COM
naine	naizih	N;PL;IN+ALL
naine	naizeči	N;SG;PROL
naine	naizettah	N;SG;PRIV
naine	naizeh	N;SG;IN+ALL
naine	naizekse	N;SG;TRANS
naine	naizes	N;SG;IN+ESS
naine	naizelpäi	N;SG;AT+ABL
naine	naiziči	N;PL;PROL
naine	naizile	N;PL;AT+ALL
naine	naizittah	N;PL;PRIV
naine	naizispäi	N;PL;IN+ABL
naine	naizespäi	N;SG;IN+ABL
naine	naizinke	N;PL;COM
naine	naizilpäi	N;PL;AT+ABL
naine	naizen	N;SG;ACC
naine	naizii	N;PL;PRT
naine	naizennu	N;SG;ESS
naine	naizet	N;PL;NOM
naine	naizikse	N;PL;TRANS
naine	naizel	N;SG;AT+ESS
naine	naizet	N;PL;ACC
naine	naizen	N;SG;GEN

piä	piäl	N;SG;AT+ESS
piä	piälöih	N;PL;IN+ALL
piä	piäs	N;SG;IN+ESS
piä	piälöis	N;PL;IN+ESS
piä	piäh	N;SG;IN+ALL
piä	piälöinny	N;PL;ESS
piä	piälöinke	N;PL;COM
piä	piälöilpäi	N;PL;AT+ABL
piä	piälöispäi	N;PL;IN+ABL
piä	piät	N;PL;ACC
piä	piälöittäh	N;PL;PRIV
piä	piäči	N;SG;PROL
piä	piäle	N;SG;AT+ALL
piä	piä	N;SG;NOM
piä	piäspäi	N;SG;IN+ABL
piä	piälöiči	N;PL;PROL
piä	piälpäi	N;SG;AT+ABL
piä	piän	N;SG;ACC
piä	piät	N;PL;NOM
piä	piäkse	N;SG;TRANS
piä	piän	N;SG;GEN
piä	piälöin	N;PL;GEN
piä	piälöikse	N;PL;TRANS
piä	piänny	N;SG;ESS
piä	piälöin	N;PL;INS
piä	piänke	N;SG;COM
piä	piättäh	N;SG;PRIV
piä	piälöil	N;PL;AT+ESS
piä	piälöi	N;PL;PRT
piä	piädy	N;SG;PRT
piä	piälöile	N;PL;AT+ALL

piälinnu	piälinnoinnu	N;PL;ESS
piälinnu	piälinnoih	N;PL;IN+ALL
piälinnu	piälinnannu	N;SG;ESS
piälinnu	piälinnois	N;PL;IN+ESS
piälinnu	piälinnoittah	N;PL;PRIV
piälinnu	piälinnoilpäi	N;PL;AT+ABL
piälinnu	piälinnakse	N;SG;TRANS
piälinnu	piälinnan	N;SG;GEN
piälinnu	piälinnas	N;SG;IN+ESS
piälinnu	piälinnan	N;SG;ACC
piälinnu	piälinnoin	N;PL;INS
piälinnu	piälinnoin	N;PL;GEN
piälinnu	piälinnoi	N;PL;PRT
piälinnu	piälinnaspäi	N;SG;IN+ABL
piälinnu	piälinnoil	N;PL;AT+ESS
piälinnu	piälinnalpäi	N;SG;AT+ABL
piälinnu	piälinnoinke	N;PL;COM
piälinnu	piälinnattah	N;SG;PRIV
piälinnu	piälinnoiči	N;PL;PROL
piälinnu	piälinnal	N;SG;AT+ESS
piälinnu	piälinnat	N;PL;ACC
piälinnu	piälinnale	N;SG;AT+ALL
piälinnu	piälinnua	N;SG;PRT
piälinnu	piälinnoispäi	N;PL;IN+ABL
piälinnu	piälinnači	N;SG;PROL
piälinnu	piälinnu	N;SG;NOM
piälinnu	piälinnah	N;SG;IN+ALL
piälinnu	piälinnoile	N;PL;AT+ALL
piälinnu	piälinnoikse	N;PL;TRANS
piälinnu	piälinnat	N;PL;NOM
piälinnu	piälinnanke	N;SG;COM

puu	puuloilpäi	N;PL;AT+ABL
puu	puuloi	N;PL;PRT
puu	puuči	N;SG;PROL
puu	puulpäi	N;SG;AT+ABL
puu	puuloikse	N;PL;TRANS
puu	puun	N;SG;ACC
puu	puuspäi	N;SG;IN+ABL
puu	puus	N;SG;IN+ESS
puu	puudu	N;SG;PRT
puu	puulois	N;PL;IN+ESS
puu	puuloittah	N;PL;PRIV
puu	puuh	N;SG;IN+ALL
puu	puunnu	N;SG;ESS
puu	puu	N;SG;NOM
puu	puun	N;SG;GEN
puu	puuloinke	N;PL;COM
puu	puuloile	N;PL;AT+ALL
puu	puuloih	N;PL;IN+ALL
puu	puule	N;SG;AT+ALL
puu	puukse	N;SG;TRANS
puu	puul	N;SG;AT+ESS
puu	puuloil	N;PL;AT+ESS
puu	puuloiči	N;PL;PROL
puu	puuloispäi	N;PL;IN+ABL
puu	puuloin	N;PL;INS
puu	puut	N;PL;NOM
puu	puuloinnu	N;PL;ESS
puu	puuttah	N;SG;PRIV
puu	puuloin	N;PL;GEN
puu	puut	N;PL;ACC
puu	puunke	N;SG;COM

sinine	sinizis	ADJ;PL;IN+ESS
sinine	sinizih	ADJ;PL;IN+ALL
sinine	sinizile	ADJ;PL;AT+ALL
sinine	sinizien	ADJ;PL;GEN
sinine	sinizin	ADJ;PL;INS
sinine	sinizeči	ADJ;SG;PROL
sinine	sinizispäi	ADJ;PL;IN+ABL
sinine	sinizettäh	ADJ;SG;PRIV
sinine	sinizet	ADJ;PL;ACC
sinine	sinizinny	ADJ;PL;ESS
sinine	sinizespäi	ADJ;SG;IN+ABL
sinine	sinizele	ADJ;SG;AT+ALL
sinine	sinizeh	ADJ;SG;IN+ALL
sinine	sinine	ADJ;SG;NOM
sinine	sinizel	ADJ;SG;AT+ESS
sinine	sinizinke	ADJ;PL;COM
sinine	sinizikse	ADJ;PL;TRANS
sinine	sinizenke	ADJ;SG;COM
sinine	sinizilpäi	ADJ;PL;AT+ABL
sinine	sinizen	ADJ;SG;ACC
sinine	sinizittäh	ADJ;PL;PRIV
sinine	sinizenny	ADJ;SG;ESS
sinine	sinisty	ADJ;SG;PRT
sinine	siniziči	ADJ;PL;PROL
sinine	sinizil	ADJ;PL;AT+ESS
sinine	sinizekse	ADJ;SG;TRANS
sinine	sinizet	ADJ;PL;NOM
sinine	sinizes	ADJ;SG;IN+ESS
sinine	sinizen	ADJ;SG;GEN
sinine	sinizelpäi	ADJ;SG;AT+ABL
sinine	sinizii	ADJ;PL;PRT

siä	siälöi	N;PL;PRT
siä	siälöinny	N;PL;ESS
siä	siälpäi	N;SG;AT+ABL
siä	siänny	N;SG;ESS
siä	siälöin	N;PL;INS
siä	siäl	N;SG;AT+ESS
siä	siälöittäh	N;PL;PRIV
siä	siän	N;SG;GEN
siä	siän	N;SG;ACC
siä	siät	N;PL;NOM
siä	siänke	N;SG;COM
siä	siä	N;SG;NOM
siä	siälöis	N;PL;IN+ESS
siä	siäh	N;SG;IN+ALL
siä	siälöiči	N;PL;PROL
siä	siät	N;PL;ACC
siä	siättäh	N;SG;PRIV
siä	siäs	N;SG;IN+ESS
siä	siäle	N;SG;AT+ALL
siä	siäkse	N;SG;TRANS
siä	siälöin	N;PL;GEN
siä	siälöikse	N;PL;TRANS
siä	siädy	N;SG;PRT
siä	siälöilpäi	N;PL;AT+ABL
siä	siälöinke	N;PL;COM
siä	siälöile	N;PL;AT+ALL
siä	siälöispäi	N;PL;IN+ABL
siä	siälöih	N;PL;IN+ALL
siä	siäči	N;SG;PROL
siä	siäspäi	N;SG;IN+ABL
siä	siälöil	N;PL;AT+ESS

suo	suonke	N;SG;COM
suo	suodu	N;SG;PRT
suo	suonnu	N;SG;ESS
suo	suoloil	N;PL;AT+ESS
suo	suos	N;SG;IN+ESS
suo	suoloin	N;PL;INS
suo	suoloile	N;PL;AT+ALL
suo	suoh	N;SG;IN+ALL
suo	suoloi	N;PL;PRT
suo	suot	N;PL;ACC
suo	suoloispäi	N;PL;IN+ABL
suo	suol	N;SG;AT+ESS
suo	suottah	N;SG;PRIV
suo	suoloilpäi	N;PL;AT+ABL
suo	suoloiči	N;PL;PROL
suo	suoči	N;SG;PROL
suo	suole	N;SG;AT+ALL
suo	suoloih	N;PL;IN+ALL
suo	suoloikse	N;PL;TRANS
suo	suospäi	N;SG;IN+ABL
suo	suoloinnu	N;PL;ESS
suo	suoloin	N;PL;GEN
suo	suolpäi	N;SG;AT+ABL
suo	suoloittah	N;PL;PRIV
suo	suoloinke	N;PL;COM
suo	suot	N;PL;NOM
suo	suon	N;SG;ACC
suo	suokse	N;SG;TRANS
suo	suo	N;SG;NOM
suo	suon	N;SG;GEN
suo	suolois	N;PL;IN+ESS

vyö	vyönny	N;SG;ESS
vyö	vyöt	N;PL;ACC
vyö	vyölöile	N;PL;AT+ALL
vyö	vyökse	N;SG;TRANS
vyö	vyöl	N;SG;AT+ESS
vyö	vyölöittäh	N;PL;PRIV
vyö	vyön	N;SG;ACC
vyö	vyölöispäi	N;PL;IN+ABL
vyö	vyön	N;SG;GEN
vyö	vyölöin	N;PL;GEN
vyö	vyödy	N;SG;PRT
vyö	vyöt	N;PL;NOM
vyö	vyöttäh	N;SG;PRIV
vyö	vyölöinny	N;PL;ESS
vyö	vyöči	N;SG;PROL
vyö	vyölpäi	N;SG;AT+ABL
vyö	vyönke	N;SG;COM
vyö	vyölöilpäi	N;PL;AT+ABL
vyö	vyölöin	N;PL;INS
vyö	vyöspäi	N;SG;IN+ABL
vyö	vyölöil	N;PL;AT+ESS
vyö	vyölöinke	N;PL;COM
vyö	vyölöis	N;PL;IN+ESS
vyö	vyölöi	N;PL;PRT
vyö	vyölöih	N;PL;IN+ALL
vyö	vyös	N;SG;IN+ESS
vyö	vyöle	N;SG;AT+ALL
vyö	vyölöiči	N;PL;PROL
vyö	vyöh	N;SG;IN+ALL
vyö	vyö	N;SG;NOM
vyö	vyölöikse	N;PL;TRANS



